### ISSUE TITLE
Interested in working together?

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [pranavlathigara/ClientServerSocket#1]
Hey,
I noticed that you copied this repository from me(I don't mind, but at least change package name). 
Anyways, I thought that I should suggest to work together on it. Interested?
And yes, I know that repository has some "code quality issues", I could quite quickly fix it and i guess while am at it convert whole rep to Kotlin.

Btw, why did you do it? I presume that you are having some sort of issues? Or maybe some features are missing?

**Comment by pranavlathigara** [comment]
Thank you for this awesome code
yes this is your code but i want to make it as library so any one can use it with ease for socket communication and working in background also

can we make it for file transfer with this code?
